"""Add bike_stations and bike_station_status tables

Revision ID: c4a5ff9f17d0
Revises: fdbec6a5419b
Create Date: 2025-06-30 14:17:03.217841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a5ff9f17d0'
down_revision: Union[str, Sequence[str], None] = 'fdbec6a5419b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_stations',
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('rental_methods', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.String(length=50), nullable=True),
    sa.Column('is_charging_station', sa.Boolean(), nullable=True),
    sa.Column('parking_type', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_bike_stations_external_id'), 'bike_stations', ['external_id'], unique=False)
    op.create_index(op.f('ix_bike_stations_region_id'), 'bike_stations', ['region_id'], unique=False)
    op.create_index(op.f('ix_bike_stations_station_id'), 'bike_stations', ['station_id'], unique=False)
    op.create_table('bike_station_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('num_bikes_available', sa.Integer(), nullable=False),
    sa.Column('num_docks_available', sa.Integer(), nullable=False),
    sa.Column('num_ebikes_available', sa.Integer(), nullable=True),
    sa.Column('num_scooters_available', sa.Integer(), nullable=True),
    sa.Column('is_renting', sa.Boolean(), nullable=False),
    sa.Column('is_returning', sa.Boolean(), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('last_reported', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['bike_stations.station_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_station_status_id'), 'bike_station_status', ['id'], unique=False)
    op.create_index(op.f('ix_bike_station_status_last_reported'), 'bike_station_status', ['last_reported'], unique=False)
    op.create_index(op.f('ix_bike_station_status_station_id'), 'bike_station_status', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bike_station_status_station_id'), table_name='bike_station_status')
    op.drop_index(op.f('ix_bike_station_status_last_reported'), table_name='bike_station_status')
    op.drop_index(op.f('ix_bike_station_status_id'), table_name='bike_station_status')
    op.drop_table('bike_station_status')
    op.drop_index(op.f('ix_bike_stations_station_id'), table_name='bike_stations')
    op.drop_index(op.f('ix_bike_stations_region_id'), table_name='bike_stations')
    op.drop_index(op.f('ix_bike_stations_external_id'), table_name='bike_stations')
    op.drop_table('bike_stations')
    # ### end Alembic commands ###
