"""Add weather_data table for OpenWeather API

Revision ID: ea49f4099f48
Revises: c4a5ff9f17d0
Create Date: 2025-06-30 14:44:41.518605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea49f4099f48'
down_revision: Union[str, Sequence[str], None] = 'c4a5ff9f17d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('temperature_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Integer(), nullable=True),
    sa.Column('wind_speed_mps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_condition', sa.String(length=255), nullable=True),
    sa.Column('weather_description', sa.String(length=255), nullable=True),
    sa.Column('precipitation_1h_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('api_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_api_timestamp'), 'weather_data', ['api_timestamp'], unique=False)
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_index(op.f('ix_weather_data_location_name'), 'weather_data', ['location_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_location_name'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_api_timestamp'), table_name='weather_data')
    op.drop_table('weather_data')
    # ### end Alembic commands ###
