"""Create vehicle_positions table

Revision ID: fdbec6a5419b
Revises: 
Create Date: 2025-06-17 14:12:06.572274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbec6a5419b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.String(length=100), nullable=True),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('bearing', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_mps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_stop_sequence', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('api_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_positions_api_timestamp'), 'vehicle_positions', ['api_timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_id'), 'vehicle_positions', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_route_id'), 'vehicle_positions', ['route_id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_trip_id'), 'vehicle_positions', ['trip_id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_vehicle_id'), 'vehicle_positions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_positions_vehicle_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_trip_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_route_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_api_timestamp'), table_name='vehicle_positions')
    op.drop_table('vehicle_positions')
    # ### end Alembic commands ###
